os: osx
language: node_js
cache:
  yarn: true
  directories:
    - node_modules
    - $HOME/Library/Caches/electron
    - $HOME/Library/Caches/electron-builder
node_js:
  - '9'
script:
  - yarn run pack
branches:
  only:
  - master
env:
  global:
    secure: m+Or12qUIo+T9/ZQ16i+5Bf/cR16O6XhQRyaJjMhutY+/OnrOMnxcgx1SnXZz2oKIZe/rbGaYEymX331ihzTny5EDr8dkM4iWj8EHsJb8m+3Y8kSGKaaYT2aVlHw8djHDpNiIzqOvPJpK9B1FHOP70XhFZvSiKJExmO3IW4i942KSxjAexq9E7URLAAGLrguuArG1C+lVlz7EgWr+2lPGH60aD8J3cHqxkY5ZdXO6qfPq/86+d9wXhMonOwGhzdKheu7hWa4dNWDtOwhVOK228Or7lxFhRRbmtQsbLCIeJF3HioM3mcOOfAA3fu+J3gxF9Y3KNQfawb6ImmkzuTfzHlenqzI1GIBwtVXrYN3PareS3PTgAqt5Iz44+hhbhfC4uLDaf+oXufXoOg8zSflyFWghe1EJjEfD0nzI+hX6p4zDfSI1U/x5Hq0XfQjDWhqdaHh17Uk5jpqqrUGi7E1/DGV0ZYbWE57/Ffcfa5ppjSbZWqTGtl6auWcuDSEOVh7vYvlVjVgRBvhOMb/BPhY9QWvO1RdB91UVM20TU4yyuSxrJ7HlmEGkQiAgTAqLF3Qse4K3GLWoT+DRxCYJUNyXQKTfNbERuOesEHAIEnQ38cQZb56BPfG7piZ/cGdiMebwAkvmR41ts4L5/SWV5SimUOeYexhk5W/wsbF10pQPjo=
